### PR TITLE
Updated to capacitor 4

### PR DESCRIPTION
**Pull request by AE1NS**

### CODE REVIEW

**Comment by AE1NS** [comment]
I also added the missing permission to android here, to close https://github.com/sparkfabrik/capacitor-plugin-idfa/issues/13

**Comment by undergroundcreative** [comment]
Hi, how can I use this in my project? I've just upgraded to Capacitor 4 but the main @sparkfabrik/capacitor-plugin-idfa plugin is failing. I'd like to use this pull which I've installed using:

npm i --save-dev sparkfabrik/capacitor-plugin-idfa#pull/16/head --force

It adds it in the devDependencies section of package.json so when I do npm run build, I'm getting:

Cannot find module '@sparkfabrik/capacitor-plugin-idfa' or its corresponding type declarations.

I get the same if I uninstall and use:

npm i --save sparkfabrik/capacitor-plugin-idfa#pull/16/head --force

 Please help! Stuck!

Thanks :)

**Comment by AE1NS** [comment]
for now you could use this:
`npm i @sparkfabrik/capacitor-plugin-idfa@github:AE1NS/capacitor-plugin-idfa`
but it would be great if @edodusi could have a look soon.

**Comment by undergroundcreative** [comment]
That's brilliant, thanks! :)

Yes, fingers crossed it will be merged with the main branch very soon so others can make use of it. 

Thanks for your help :)

**Comment by edodusi** [comment]
I can merge it, unfortunately I cannot test it so if @undergroundcreative can also confirm this is working fine I will proceed

**Comment by edodusi** [comment]
One thing @AE1NS, are we breaking compatibility with Capacitor < 4?

**Comment by AE1NS** [comment]
Could be the case maybe, but its no problem, because I raised this package version to 4. Everyone with capacitor 3 can still install the 3.x versions of this plugin.

**Comment by AE1NS** [comment]
@undergroundcreative can you confirm that everything is working so far with your installed package from my git branch? So @edodusi can merge the pull request and publish an official npm version.

**Comment by undergroundcreative** [comment]
@AE1NS @edodusi I haven't been able to test it yet as I'm having problems with several other plugins :( I've been working on updating to Capacitor 4 for well over a week now.. loads of build errors and conflicts. I'll let you know when I do manage to test it though.

**Comment by edodusi** [comment]
Ok, with another succesfull test I will merge it and create the new release

**Comment by AE1NS** [comment]
@undergroundcreative any news to your upgrade progress / test? :)

**Comment by undergroundcreative** [comment]
@AE1NS I've just managed to test it on both iOS and Android and it seems to be working correctly :)

**Comment by AE1NS** [comment]
@edodusi what do you think? Can it be merged?

**Comment by nseb** [comment]
@edodusi any idea for release date ?

**Comment by edodusi** [comment]
here I am, I'm merging this now and will release soon!

**Pull request merged**
