### PR TITLE
feat: capacitor 5 support

### LINKED ISSUE #29: Capacitor 5
https://capacitorjs.com/docs/next/updating/plugins/5-0

### PR DESCRIPTION
**Pull request by AE1NS**
Closes https://github.com/sparkfabrik/capacitor-plugin-idfa/issues/29

### CODE REVIEW

**Comment by AE1NS** [comment]
@edodusi do you think you get time soon to have a look?

**Comment by hoi4** [comment]
It would be awesome to have this released 😇 Thank you in advance! @edodusi

**Comment by AE1NS** [comment]
I will switch to this one for the future https://github.com/capacitor-community/advertising-id where capacitor devs are contributors, so it should be well maintained in long term.

**Comment by edodusi** [comment]
I see now that the capacitor community have created a module that does basically the same thing, as reported by @AE1NS. So I will recommend to switch to that "official" module instead of this one, which I will discontinue.

I will now merge this and prepare a new release, so that you could switch whenever you can.

Thank you for your contributions

**Pull request merged**
